### PR TITLE
Remove the Natural instances

### LINKED ISSUE #1031: Natural values don't fit into an sql database
https://github.com/yesodweb/persistent/blob/6665283c837d66f649d4a13c48b273d109017bdd/persistent/Database/Persist/Sql/Class.hs#L493-L494

This fails to round-trip for naturals bigger than a Word64.
I would argue that this instance should be removed.
If you don't need naturals that big, then just use the Word64 instance instead.
If you do, then you expect them to roundtrip.

### PR DESCRIPTION
**Pull request by parsonsmatt**
Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

Fixes #1031

### CODE REVIEW

**Comment by erikd** [comment]
I should stop using it then :).

File: persistent/Database/Persist/Class/PersistField.hs [hunk 1]
```diff
@@ -322,11 +324,43 @@ instance PersistField UTCTime where
...
+
+instance
+  TypeError
+    ( 'Text "The instance of PersistField for the Natural type was removed."
+    ':$$: 'Text "Please see the documentation for OverflowNatural if you want to "
+    ':$$: 'Text "continue using the old behavior or want to see documentation on "
+    ':$$: 'Text "why the instance was removed."
+    ':$$: 'Text ""
+    ':$$: 'Text "This error instance will be removed in a future release."
+    )
```
Comment (MaxGabriel) [inline persistent/Database/Persist/Class/PersistField.hs]: This is pretty sick

Comment (erikd) [reply persistent/Database/Persist/Class/PersistField.hs]: That is the good kind of sick right?
