### PR TITLE
Fix duplicate entity checks

### LINKED ISSUE #1288: The duplicate entity check doesn't work transitively
So the fix in https://github.com/yesodweb/persistent/pull/1255 isn't quite enough. The tests in #1287 document the issue.

With the following format:

```haskell

module A where
  
  mkPersist sqlSettings [persistLowerCase|
    A
      name Text
    |]

module B where

  import A
  mkPersistWith sqlSettings $(discoverEntities) [persistLowerCase|
    B
      a AId
  |]

module C where

  import B

  mkPersistWith sqlSettings $(discoverEntities) [persistLowerCase|
    C
      b BId
    |]
```

You'll get duplicate name errors because the `mkPersistWith` in `C` is trying to make models for `A`. `A` is not available for `lookupTypeName`, but it is still present in the input entity list.

Seems like it should be straightforward to just *not* generate things from the input list??

### PR DESCRIPTION
**Pull request by parsonsmatt**
Before submitting your PR, check that you've:

- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock
- [x] Ran `stylish-haskell` on any changed files.
- [x] Adhered to the code style (see the `.editorconfig` file for details)

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

Closes #1288

### CODE REVIEW

File: persistent/Database/Persist/TH.hs [hunk 1]
```diff
@@ -773,7 +771,11 @@ mkPersistWith mps preexistingEntities ents' = do
             $ predefs
         entityMap =
             constructEntityMap allEnts
-    ents <- filterM shouldGenerateCode allEnts
+        newEnts =
+            Set.toList $
+                Set.fromList allEnts
+                Set.\\ Set.fromList (map unbindEntityDef preexistingEntities)
```
Comment (parsonsmatt) [inline persistent/Database/Persist/TH.hs:777]: Lol, sigh, alas, oh well, so silly,,,

**Comment by parsonsmatt** [comment]
mm no this is broken still

looks like the code in the `symbolToField` stuff needs to do a qualified lookup

File: persistent/test/Database/Persist/TH/SharedPrimaryKeyImportedSpec.hs [hunk 2]
```diff
@@ -28,7 +28,7 @@ import Database.Persist.TH.SharedPrimaryKeySpec (User, UserId)
 
 mkPersistWith sqlSettings $(discoverEntities) [persistLowerCase|
 
-Profile
+ProfileX
```
Comment (parsonsmatt) [inline persistent/test/Database/Persist/TH/SharedPrimaryKeyImportedSpec.hs:31]: `persistent` now fails to generate code for `Profile` because `Profile` is already a table defined in `discoverEntities`.

**Review by parsonsmatt — COMMENTED** [review]
OK, I've got it fixed. Mostly by *skipping* the transformation from `ModelNameId` to `Key ModelName` if we're not in the `mpsGeneric` mode.

Another bug from #1204 :\
