### PR TITLE
Fix a name shadowing warning (#1406)

### LINKED ISSUE #1406: Incorrect shadowed name warning
For a trivial schema definition (with persistent 2.14.0.1):
```
share
  [ mkPersist sqlSettings
  , mkMigrate "migrateCardanoDb"
  , mkEntityDefList "entityDefs"
  , deriveShowFields
  ]
  [persistLowerCase|

  SchemaVersion
    stageOne Int
    stageTwo Int
    stageThree Int
    deriving Eq
  |]
```
I an getting strange shadowed name warnings like:
```
rc/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageTwo’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageThree’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageOne’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageThree’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageOne’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...

src/Cardano/Db/Schema.hs:47:1: error: [-Wname-shadowing, -Werror=name-shadowing]
    This binding for ‘schemaVersionStageTwo’ shadows the existing binding
      defined at src/Cardano/Db/Schema.hs:47:1
   |
47 | share
   | ^^^^^...
```
This worked up until version `2.14`. Adding the constraint `persistent < 2.13.3.4` makes it build again.

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR fixes #1406 which noticed that the code generated name shadowing warnings.

The specific problem si that we'd generate code like:

```haskell
case someRecord of
  Constructor { fieldName = fieldName } -> ...
```

where `fieldName` shadowed `fieldName`.

Before submitting your PR, check that you've:

- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock
- [x] Ran `stylish-haskell` on any changed files.
- [x] Adhered to the code style (see the `.editorconfig` file for details)

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

File: persistent/Database/Persist/TH.hs [hunk 1]
```diff
@@ -1462,9 +1462,15 @@ fieldUpd :: Name -- ^ constructor name
...
-    [ Match (RecP con pats) (NormalB body) []]
+    -> Q Exp
+fieldUpd con names record name new = do
+    pats <-
+        fmap mconcat $ forM names $ \k -> do
+            varName <- VarP <$> newName (nameBase k)
+            pure [(k, varName) | k /= name]
+
+    pure $ CaseE record
+        [ Match (RecP con pats) (NormalB body) []]
```
Comment (parsonsmatt) [inline persistent/Database/Persist/TH.hs:1473]: This is the function that was introducing the problem.

File: persistent/Database/Persist/TH.hs [hunk 2]
```diff
@@ -1462,9 +1462,15 @@ fieldUpd :: Name -- ^ constructor name
...
     -> Name -- ^ field name to update
     -> Exp -- ^ new value
-    -> Exp
-fieldUpd con names record name new = CaseE record
-    [ Match (RecP con pats) (NormalB body) []]
+    -> Q Exp
+fieldUpd con names record name new = do
+    pats <-
+        fmap mconcat $ forM names $ \k -> do
+            varName <- VarP <$> newName (nameBase k)
```
Comment (parsonsmatt) [inline persistent/Database/Persist/TH.hs:1469]: And, this line is the real fix. By creating a `newName`, we're guaranteeing that the variable is fresh and uncapturable and isn't shadowing anything.

@fumieval This is one of those tricky things about `TemplateHaskell` - it's so easy to use and make names that can cause warnings and bugs! I do it all the time and I really ought to write up a lil' how to on the matter.

File: persistent/test/Database/Persist/TH/OverloadedLabelSpec.hs [hunk 3]
```diff
@@ -13,6 +13,8 @@
 {-# LANGUAGE TypeFamilies               #-}
 {-# LANGUAGE UndecidableInstances       #-}
 
+{-# OPTIONS_GHC -Wname-shadowing -Werror=name-shadowing #-}
```
Comment (parsonsmatt) [inline persistent/test/Database/Persist/TH/OverloadedLabelSpec.hs:16]: This warning is the 'test' for the feature.
