### PR TITLE
Fix anomalies in migration of integer columns in MySQL 8 (#1358)

### LINKED ISSUE #1358: Repeated migrations of an Int32 column in MySQL 8
*This issue describes the problem - PRs will follow both to extend the tests and to fix `persistent-mysql`.*

When running against MySQL 8.0.28, repeated, spurious migrations looking like this are produced for `Int32` columns:

```
ALTER TABLE `idempotency` CHANGE `field8` `field8` INT(11) NOT NULL
```

Internally, the behaviour for `Int64` is also dubious, but we get away with it at present - more about that below.

The problem is the "display width" - the "(11)" here - which has no effect on the stored data, and was [deprecated at MySQL 8.0.17](https://dev.mysql.com/doc/refman/8.0/en/numeric-type-attributes.html).  At some point (maybe 8.0.19) it stopped being included in the column type shown in the information_schema.  For reasons spelt out below, `findAlters` in `Database.Persist.MySQL` still expects to see "INT(11)", but now only gets "INT", so it generates a migration.  The attempted table alteration doesn't actually change anything on the server, so this recurs every time migration is calculated.

The code is wrong in two places:

  - When `parseColumnType` decodes an integer type, but the display width it expects is absent, it produces `SqlOther`.  Therefore, with MySQL 8, it gives `SqlOther "int"` and `SqlOther "bigint"` for 32- and 64-bit integers, instead of the correct decodings `SqlInt32` and `SqlInt64`.
  - `findAlters` compares the results of applying `showSqlType` both to the expected column and to the column type decoded from `parseColumnType`.  Unfortunately, `showSqlType SqlInt32` is "INT(11)" which does not match the "int" from `showSqlType (SqlOther "int")`.  This is unnecessary, even in MySQL 5.7, since eleven is the default display width for INT.  Indeed - inconsistently - `showSqlType SqlInt64` is simply "BIGINT", which is why we get away with matching it against `SqlOther "bigint"`, even though the latter isn't the intended decoding of the type.

This problem is not picked up by the migration idempotency test, since it has only a 64-bit integer column.  PR on its way to fix that first!

### PR DESCRIPTION
**Pull request by paul-rouse**
Fixes #1358.  I believe this remains compatible with older versions of MySQL, so should be a minor version bump.
 
Before submitting your PR, check that you've:

- [x] Ran `stylish-haskell` on any changed files.
- [x] Adhered to the code style (see the `.editorconfig` file for details)

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

File: persistent-mysql/Database/Persist/MySQL.hs [hunk 1]
```diff
@@ -1013,10 +1023,12 @@ showSqlType :: SqlType
             -> String
 showSqlType SqlBlob    Nothing    _     = "BLOB"
 showSqlType SqlBlob    (Just i)   _     = "VARBINARY(" ++ show i ++ ")"
+-- The non-default display width "(1)" is kept for now to avoid differences
+-- between persistent versions running against older MySQL versions (eg 5.7):
 showSqlType SqlBool    _          _     = "TINYINT(1)"
 showSqlType SqlDay     _          _     = "DATE"
 showSqlType SqlDayTime _          _     = "DATETIME"
-showSqlType SqlInt32   _          _     = "INT(11)"
+showSqlType SqlInt32   _          _     = "INT"
```
Comment (parsonsmatt) [inline persistent-mysql/Database/Persist/MySQL.hs:1031]: This comment doesn't appear to agree with the code change - can you clarify?

File: persistent-mysql/Database/Persist/MySQL.hs [hunk 2]
```diff
@@ -827,9 +827,19 @@ data ColumnInfo = ColumnInfo
...
+-- the bare type in `ciColumnType ci`, or the type adorned with the expected
+-- value for the display width (ie the defaults for int and bigint, or the
+-- value explicitly set in `showSqlType` for SqlBool).
+--
+parseColumnType "tinyint" ci
+    | ciColumnType ci == "tinyint" || ciColumnType ci == "tinyint(1)" = return (SqlBool, Nothing)
+parseColumnType "int" ci
+    | ciColumnType ci == "int"     || ciColumnType ci == "int(11)"    = return (SqlInt32, Nothing)
+parseColumnType "bigint" ci
+    | ciColumnType ci == "bigint"  || ciColumnType ci == "bigint(20)" = return (SqlInt64, Nothing)
```
Comment (parsonsmatt) [inline persistent-mysql/Database/Persist/MySQL.hs:841]: does it maybe make sense to do a `Just _ <- Text.stripPrefix "tinyint" ` pattern? That would match `tinyint`, `tinyint(1)`, and `tinyint(2345)` etc.

**Review by parsonsmatt — APPROVED** [review]
A few questions but otherwise looks great, thank you!

File: persistent-mysql/Database/Persist/MySQL.hs (hunk 1 above)
Comment (paul-rouse) [reply persistent-mysql/Database/Persist/MySQL.hs:1031]: It's not a great comment - I'll add a commit to try to improve it!  The point is I'm trying to avoid changing *anything* about what is put into the information schema in MySQL 5.7 and early members of the 8.X series.  In 5.7, `INT` gets a default display width `(11)` anyway, so I felt it would be clearer in the future to omit it here (as was already done for `BIGINT`).  However  `(1)` is not the default for `TINYINT`, and omitting it would make MySQL 5.7 add  `(4)` instead in the information schema.  It doesn't affect the data storage for the column itself, of course, but the different information schema might cause spurious migrations in `persistent`, or be incompatible with some external program the user might depend upon.

File: persistent-mysql/Database/Persist/MySQL.hs (hunk 2 above)
Comment (paul-rouse) [reply persistent-mysql/Database/Persist/MySQL.hs:841]: Again, I am trying to avoid changing anything for MySQL 5.7 and early 8.X.  These versions will always report the display width, so I thought it best to match it exactly, as before, to avoid including cases which were not included in `persistent-mysql-2.13.1.0`.  The addition is the matching of the bare type, eg `int`, which will only be reported by later 8.X versions

**Comment by paul-rouse** [comment]
@parsonsmatt I will add a commit to improve the comment in the code, but would you like me to merge and release then?  I tend to leave things `persistent` to you, but quite happy to do this.

**Comment by paul-rouse** [comment]
I've got this one - just remembered it's sitting around.
