### PR TITLE
Shared Primary Keys

### LINKED ISSUE #1147: SQL types are wrong for shared primary keys
This module demonstrates the problem.

```haskell
{-# LANGUAGE TypeApplications, DeriveGeneric #-}
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE QuasiQuotes #-}
{-# LANGUAGE TemplateHaskell #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE DerivingStrategies #-}
{-# LANGUAGE StandaloneDeriving #-}

module SharedPrimaryKeyTest where

import TemplateTestImports

import Database.Persist
import Database.Persist.Sql
import Database.Persist.Sql.Util
import Database.Persist.TH

share [ mkPersist sqlSettings ] [persistLowerCase|

User
    name    String

Profile
    Id      UserId
    email   String

|]

specs :: Spec
specs = describe "Shared Primary Keys" $ do
```

As of now, this doesn't even compile.

```
/home/matt/Projects/persistent/persistent-template/test/SharedPrimaryKeyTest.hs:23:51: error:
    • Not in scope: type constructor or class ‘UserId’
    • In the quasi-quotation:
        [persistLowerCase|
            
User        
    name    String
            
Profile     
    Id      UserId
    email   String
            
|]          
   |        
23 | share [ mkPersist sqlSettings ] [persistLowerCase|
   |                                                   ^...
   
```

Switching `Profile` to using a `userId UserId; Primary userId` works. But that's pretty weird, I'd except `UserId` to have the same resolution with `Id` as it would for `userId`.

You can get Clever by doing a `(Key User)` instead. Then the `PersistFieldSql` is right, but the actual `entityId` on the field definition is wrong.

### PR DESCRIPTION
**Pull request by parsonsmatt**
Before submitting your PR, check that you've:

- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

Fixes #1147

### CODE REVIEW

File: persistent-template/Database/Persist/TH.hs [hunk 1]
```diff
@@ -1677,7 +1677,7 @@ liftAndFixKeys entityMap EntityDef{..} =
     [|EntityDef
         entityHaskell
         entityDB
-        entityId
+        $(liftAndFixKey entityMap entityId)
```
Comment (parsonsmatt) [inline persistent-template/Database/Persist/TH.hs:1680]: This is the actual fix.
