### PR TITLE
Foreign key improvements

### LINKED ISSUE #957: persistent's quasi quoter wrongly rejects foreign keys that are not primary keys.
[This line](https://github.com/yesodweb/persistent/blob/master/persistent/Database/Persist/Quasi.hs#L227) checks that the foreign key matches the primary key of the referred table. This is needlessly restrictive as foreign keys are allowed to point to unique constraints too.

I was trying to work around persistent's inability to define unique constraints that involve the id key, but now I've been hamstrung by the fact that even if I define them myself I can't define the proper foreign keys because they are different from the primary key...

### PR DESCRIPTION
**Pull request by parsonsmatt**
Before submitting your PR, check that you've:

- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

Continuation of #1121 

Fixes #957

### CODE REVIEW

File: persistent-postgresql/Database/Persist/Postgresql.hs [hunk 1]
```diff
@@ -942,7 +943,8 @@ getColumn getter tableName' [PersistText columnName, PersistText isNullable, Per
                           , cDefault = fmap stripSuffixes d''
                           , cDefaultConstraintName = Nothing
                           , cMaxLen = Nothing
-                          , cReference = ref
+                          -- TODO: Fix cascade reference is ignored
```
Comment (parsonsmatt) [inline persistent-postgresql/Database/Persist/Postgresql.hs:946]: looks like this is available [here](https://www.postgresql.org/docs/9.0/infoschema-referential-constraints.html)

File: persistent-postgresql/Database/Persist/Postgresql.hs [hunk 2]
```diff
@@ -1066,14 +1068,15 @@ findAlters defs edef col@(Column name isNull sqltype def _defConstraintName _max
                                     a
                                     [name]
                                     (Util.dbIdColumnsEsc escape refdef)
+                                    -- TODO: Fix cascade reference is ignored
```
Comment (parsonsmatt) [inline persistent-postgresql/Database/Persist/Postgresql.hs:1071]: seems like we can just copy it on down

File: persistent-template/Database/Persist/TH.hs [hunk 3]
```diff
@@ -379,32 +406,39 @@ mkEntityDefSqlTypeExp emEntities entityMap ent =
...
-                        -- SqlTypeExp. However, there's one corner case: if there's
-                        -- a list of entity IDs, the datatype for the ID has not
-                        -- yet been created, so the compiler will fail. This extra
-                        -- clause works around this limitation.
-                        FTList _ -> SqlType' SqlString
-                        _ -> SqlTypeExp ftype
+            Right _ ->
+                SqlType' SqlString
+            Left (Just FTKeyCon) ->
+                SqlType' SqlString
```
Comment (parsonsmatt) [inline persistent-template/Database/Persist/TH.hs:412]: this seems extremely dubious to me

**Comment by parsonsmatt** [comment]
@erikd y'all wanna take a look at this?
