### PR TITLE
Type error on upsert.

### LINKED ISSUE #796: Deprecate upsert?
The `upsert` function inserts or updates an existing record. It works fine if there's one uniqueness constraint, but if there are two it doesn't know which to use, and throws an exception. This is pretty lame: you wouldn't think that adding a new uniqueness constraint would cause a runtime exception in a related area of your code. Users should just use `upsertBy`, or if their database supports a way of not specifying it, use that functionality (e.g. the MySQL module exposes `insertOnDuplicateKeyUpdate`; I think Postgres requires specifying the column(s)).

This would resolve issues like #768 and avoid all the documentation of this caveat in #785.

### LINKED ISSUE #868: Type Error on Unsafe Upsert Functions
There are a couple of unsafe functions in `persistent`. It would be nice to fix them.

[`upsert`](https://www.stackage.org/haddock/lts-13.15/persistent-2.9.1/Database-Persist-Class.html#v:upsert) fails at runtime if there isn't exactly one uniqueness constraint. We could have a type class `UniqueUnique` (or, probably better named, `OnlyOneUnique`) with valid instances being generated for entities that possess exactly one key. Other entities would instead have `TypeError`-laden instances. This moves failure from run-time to compile-time with very little cost to end users.

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR introduces a few type classes that are required on `upsert` and related functions that have expectations on how many unique keys a record has.

Instances for these classes are generated automatically, and "failing" instances get informative "TypeError"s when you misuse them.

Fixes #868 
Fixes #796 

---

Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Weird, I am getting test suite failures locally for MongoDB:

````
  src/Init.hs:106:32: 
  1) persistent.putMany handles conflicts by replacing old keys with new records
       expected: [Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea9c3d4613542ae00082a}, entityVal = Upsert {upsertEmail = "putMany4", upsertAttr = "new", upsertExtra = "", upsertAge = 2}},Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea9c3d4613542ae00082b}, entityVal = Upsert {upsertEmail = "putMany5", upsertAttr = "new", upsertExtra = "", upsertAge = 2}},Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea7b6d46135390b00082d}, entityVal = Upsert {upsertEmail = "putMany6", upsertAttr = "new", upsertExtra = "", upsertAge = 2}},Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea7b6d46135390b00082c}, entityVal = Upsert {upsertEmail = "putMany7", upsertAttr = "new", upsertExtra = "", upsertAge = 2}}]
        but got: [Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea7b6d46135390b00082a}, entityVal = Upsert {upsertEmail = "putMany4", upsertAttr = "new", upsertExtra = "", upsertAge = 2}},Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea7b6d46135390b00082b}, entityVal = Upsert {upsertEmail = "putMany5", upsertAttr = "new", upsertExtra = "", upsertAge = 2}},Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea7b6d46135390b00082d}, entityVal = Upsert {upsertEmail = "putMany6", upsertAttr = "new", upsertExtra = "", upsertAge = 2}},Entity {entityKey = UpsertKey MongoKey {unMongoKey = 5caea7b6d46135390b00082c}, entityVal = Upsert {upsertEmail = "putMany7", upsertAttr = "new", upsertExtra = "", upsertAge = 2}}]

  To rerun use: --match "/persistent/putMany/handles conflicts by replacing old keys with new records/"

```

The IDs are different. I did not get these earlier when I was refactoring the test suite, and they don't appear to show up in CI?

File: persistent-mongoDB/test/EmbedTestMongo.hs [hunk 1]
```diff
@@ -1,5 +1,6 @@
 {-# OPTIONS_GHC -fno-warn-unused-binds -fno-warn-orphans -O0 #-}
 {-# LANGUAGE DeriveDataTypeable #-}
+{-# LANGUAGE UndecidableInstances #-}
```
Comment (parsonsmatt) [inline persistent-mongoDB/test/EmbedTestMongo.hs]: This change requires `UndecidableInstances`. I give a nice error message for upgrading.

File: persistent-test/src/UpsertTest.hs [hunk 2]
```diff
@@ -165,3 +165,48 @@ specsWith runDb handleNull handleKey = describe "UpsertTests" $ do
               Just 2
           Don'tUpdateNull ->
               Nothing
+
+  describe "putMany" $ do
```
Comment (parsonsmatt) [inline persistent-test/src/UpsertTest.hs]: Moved from the `PersistentTest` module so that `mongoDB` could skip them for now.

File: persistent/Database/Persist/Class/PersistUnique.hs [hunk 3]
```diff
@@ -127,13 +137,12 @@ class (PersistUniqueRead backend, PersistStoreWrite backend) =>
...
             Nothing -> Just `liftM` insert datum
             Just _ -> return Nothing
+
     -- | Update based on a uniqueness constraint or insert:
     --
     -- * insert the new record if it does not exist;
     -- * If the record exists (matched via it's uniqueness constraint), then update the existing record with the parameters which is passed on as list to the function.
     --
-    -- Throws an exception if there is more than 1 uniqueness constraint.
-    --
```
Comment (parsonsmatt) [inline persistent/Database/Persist/Class/PersistUnique.hs]: :wave:

**Comment by parsonsmatt** [comment]
Do we need to bump the major versions of the component libraries? eg `persistent-mysql` exports `Database.Persist.Sql` which has these changes. But it's interface does not change at all, and you need to depend on `persistent` anyway to use this stuff.

**Comment by parsonsmatt** [comment]
Ah, dang. We can't do `TypeError` unless we drop support for GHC 7.10.3.
